# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-01 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmebot',
            name='body',
        ),
        migrations.RemoveField(
            model_name='groupmebot',
            name='date',
        ),
    ]
