# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20161101_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmebot',
            name='avatar_url',
            field=models.URLField(default='fake_url'),
        ),
        migrations.AddField(
            model_name='groupmebot',
            name='callback_url',
            field=models.URLField(default='fake_url'),
        ),
    ]
