# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 21:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20161102_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmebot',
            name='avatar_url',
            field=models.URLField(default='fake_url', validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='groupmebot',
            name='callback_url',
            field=models.URLField(default='fake_url', validators=[django.core.validators.URLValidator]),
        ),
    ]
