# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20161110_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmebot',
            name='victimID',
            field=models.IntegerField(unique=True),
        ),
    ]
