# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20161110_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmebot',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
